# Generated by Django 5.0.7 on 2024-07-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparks', '0001_initial'),
        ('first', '0005_carmodel_created_at_carmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='auto_park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoparks.autopark'),
            preserve_default=False,
        ),
    ]
