# Generated by Django 5.0.7 on 2024-08-12 19:55

from django.db import migrations, models

import core.services.file_services


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_carmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_services.FileService.upload_car_photo),
        ),
    ]
